meta_name: "Active Buddy"
meta_title: "Active buddy - Event"
meta_description: "Be active and get in shape with Active Buddy. Find sport enthusiasts to train with easily."
meta_image: "cover.png" # should exist in `app/assets/images/`
